name: keep_serv00

on:
  schedule:
    - cron: '0 */5 * * *'  # 每 5 小时执行一次
  workflow_dispatch:  # 支持手动执行  

env:
  SERVERS_JSON: ${{ secrets.SERVERS_JSON }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  
jobs:
  keep_serv00:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install jq
        run: sudo apt-get install -y jq 

      - name: Execute SSH Login Script
        run: |
          echo "$SERVERS_JSON" > servers.json
          chmod +x ./keep_serv00.sh 
          ./keep_serv00.sh servers.json "$TG_TOKEN" "$CHAT_ID"
        env:
          PATH: /usr/bin:$PATH
